const emailRegex = '^\\S+@\\S+\\.\\S+$';
const MAX_WIDTH_SCREEN = 1280;
const MIN_WIDTH_SCREEN = 768;

const INIT_CARD_MAX_SCREEN = 12;
const INIT_CARD_MEDIUM_SCREEN = 8;
const INIT_CARD_MIN_SCREEN = 5;
const STEP_MAX_WIDTH_SCREEN = 3;
const STEP_MEDIUM_AND_MIN_WIDTH_SCREEN = 2;

export {
  emailRegex,
  MAX_WIDTH_SCREEN,
  MIN_WIDTH_SCREEN,
  INIT_CARD_MAX_SCREEN,
  INIT_CARD_MEDIUM_SCREEN,
  INIT_CARD_MIN_SCREEN,
  STEP_MAX_WIDTH_SCREEN,
  STEP_MEDIUM_AND_MIN_WIDTH_SCREEN
};
